version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: fusionpact-backend
    ports:
      - "3001:5000" # Expose backend service on port 5000
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    container_name: fusionpact-frontend
    ports:
      - "3000:80" # Expose frontend service on port 3000
    volumes:
      - ./frontend:/var/www/html  
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend 