
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    static_configs:
      - targets: ['34.215.182.184:9090']

  - job_name: 'backend'
    metrics_path: '/metrics'  # Path to scrape metrics from (default is /metrics)
    static_configs:
      - targets: ['34.215.182.184:5000']  # Replace with your backend service host and port
 

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['34.215.182.184:9100']